/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket.view;

import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import supermarket.controller.OrderController;
import supermarket.controller.OrderDetailsController;
import supermarket.dto.OrderDetailsDto;
import supermarket.dto.OrderDto;

/**
 *
 * @author Sanjaya Prasad
 */
public class CancelOrderView extends javax.swing.JFrame {

    private OrderDetailsController orderDetailsController;
    private List<OrderDetailsDto> orderDetailsDtos = new ArrayList<>();
    private OrderController orderController = new OrderController();

    public CancelOrderView() {
        orderDetailsController = new OrderDetailsController();
        initComponents();
        loadTable1();
        loadTable2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemsData = new javax.swing.JTable();
        txtAdd = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        txtItemID = new javax.swing.JTextField();
        btnOrderData = new javax.swing.JButton();
        lblCustData = new javax.swing.JLabel();
        lblRoomData = new javax.swing.JLabel();
        lblCustomerData = new javax.swing.JLabel();
        lblRMData = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderDetailsData = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CANCEL ORDERS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Order ID :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Item ID :");

        txtOrderID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblItemsData.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblItemsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItemsData.setRowHeight(25);
        jScrollPane1.setViewportView(tblItemsData);

        txtAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAdd.setText("Add");
        txtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddActionPerformed(evt);
            }
        });

        btnCancelOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        txtItemID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnOrderData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOrderData.setText("Search");
        btnOrderData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDataActionPerformed(evt);
            }
        });

        lblCustData.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblRoomData.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblCustomerData.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblRMData.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblRMData.setText("gggg");

        tblOrderDetailsData.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblOrderDetailsData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrderDetailsData.setRowHeight(25);
        jScrollPane2.setViewportView(tblOrderDetailsData);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Quantity :");

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Discount :");

        txtDis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerData)
                    .addComponent(lblRMData, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancelOrder)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(lblCustData))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrderData)
                        .addGap(215, 215, 215)
                        .addComponent(lblRoomData))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDis, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderData))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustData)
                    .addComponent(lblCustomerData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtItemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(txtAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelOrder)
                .addGap(179, 179, 179)
                .addComponent(lblRoomData)
                .addGap(227, 227, 227)
                .addComponent(lblRMData, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        AddToTable();
    }//GEN-LAST:event_txtAddActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        CancelOrder();
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOrderDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDataActionPerformed
        SearchOrderDetails();
    }//GEN-LAST:event_btnOrderDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelOrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelOrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnOrderData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCustData;
    private javax.swing.JLabel lblCustomerData;
    private javax.swing.JLabel lblRMData;
    private javax.swing.JLabel lblRoomData;
    private javax.swing.JTable tblItemsData;
    private javax.swing.JTable tblOrderDetailsData;
    private javax.swing.JButton txtAdd;
    private javax.swing.JTextField txtDis;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
private void loadTable1() {
        String[] columns = {"Order ID", "Item ID", "Quantity", "Discount", "Total Price"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tblOrderDetailsData.setModel(defaultTableModel);

        CenterCellRenderer centerRenderer = new CenterCellRenderer();
        for (int i = 0; i < tblOrderDetailsData.getColumnCount(); i++) {
            TableColumn column = tblOrderDetailsData.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }
        JTableHeader header = tblOrderDetailsData.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16));
    }

    private void loadTable2() {
        String[] columns = {"Item ID", "Quantity", "Discount"};

        DefaultTableModel defaultTableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        tblItemsData.setModel(defaultTableModel);

        CenterCellRenderer centerRenderer = new CenterCellRenderer();
        for (int i = 0; i < tblItemsData.getColumnCount(); i++) {
            TableColumn column = tblItemsData.getColumnModel().getColumn(i);
            column.setCellRenderer(centerRenderer);
        }
        JTableHeader header = tblItemsData.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16));
    }

    private void SearchOrderDetails() {
        try {

            List<OrderDetailsDto> dtos = orderDetailsController.get(txtOrderID.getText());
            if (dtos == null || dtos.size() == 0) {
                JOptionPane.showMessageDialog(this, "Order Not Found");
            } else {
                for (OrderDetailsDto e : dtos) {
                    Object rows[] = {
                        e.getOrderID(),
                        e.getItemID(),
                        e.getOrderQty(),
                        e.getDiscount(),
                        e.getTotalPrice()
                    };
                    DefaultTableModel dtm = (DefaultTableModel) tblOrderDetailsData.getModel();
                    dtm.addRow(rows);
                }

                CenterCellRenderer centerRenderer = new CenterCellRenderer();
                for (int i = 0; i < tblOrderDetailsData.getColumnCount(); i++) {
                    TableColumn column = tblOrderDetailsData.getColumnModel().getColumn(i);
                    column.setCellRenderer(centerRenderer);
                }
                JTableHeader header = tblOrderDetailsData.getTableHeader();
                header.setFont(new Font("Arial", Font.BOLD, 16));
            }

        } catch (Exception ex) {
            Logger.getLogger(CancelOrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }

    private void clear() {
        txtDis.setText("");
        txtItemID.setText("");
        txtQty.setText("");
        txtOrderID.setText("");
        DefaultTableModel model1 = (DefaultTableModel) tblOrderDetailsData.getModel();
        model1.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) tblItemsData.getModel();
        model2.setRowCount(0);
    }
    private void clear2() {
        txtDis.setText("");
        txtItemID.setText("");
        txtQty.setText("");  
    }
    private void AddToTable() {
        try {

            OrderDetailsDto orderDetailsDto = new OrderDetailsDto();
            orderDetailsDto.setItemID(txtItemID.getText());
            orderDetailsDto.setOrderQty(Double.parseDouble(txtQty.getText()));
            orderDetailsDto.setDiscount(Double.parseDouble(txtDis.getText()));
            orderDetailsDtos.add(orderDetailsDto);

            Object[] rowData = {orderDetailsDto.getItemID(), orderDetailsDto.getOrderQty(), orderDetailsDto.getDiscount()};
            DefaultTableModel dtm = (DefaultTableModel) tblItemsData.getModel();
            dtm.addRow(rowData);
            CenterCellRenderer centerRenderer = new CenterCellRenderer();
            for (int i = 0; i < tblItemsData.getColumnCount(); i++) {
                TableColumn column = tblItemsData.getColumnModel().getColumn(i);
                column.setCellRenderer(centerRenderer);
            }
            JTableHeader header = tblItemsData.getTableHeader();
            header.setFont(new Font("Arial", Font.BOLD, 16));
            clear2();
        } catch (Exception ex) {
            Logger.getLogger(OrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void CancelOrder() {
        try {

            OrderDto orderDto = new OrderDto();
            orderDto.setOrderID(txtOrderID.getText());
            orderDto.setOrderDetailsDto(orderDetailsDtos);

            String resp = orderController.cancelOrder(orderDto);
            JOptionPane.showMessageDialog(this, resp);
            clear();
        } catch (Exception ex) {
            Logger.getLogger(CancelOrderView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
